name: Build & Deploy Spring App

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot for Beginners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Install Maven dependencies
        run: mvn -B install --file pom.xml

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn -B clean package --file pom.xml
